-- 코드를 입력하세요
SELECT SUBSTR(TIMES,1, 4) AS YEAR,
       TO_NUMBER(SUBSTR(TIMES, 5, 2)) AS MONTH,
       GENDER,
       COUNT(1) AS USERS
FROM 
    (SELECT TO_CHAR(B.SALES_DATE, 'YYYYMM') AS TIMES,
           A.GENDER,
           COUNT(1) KEEP(DENSE_RANK FIRST ORDER BY A.USER_ID, TO_CHAR(B.SALES_DATE, 'YYYYMM')) AS USERS
      FROM USER_INFO A, ONLINE_SALE B
     WHERE A.USER_ID = B.USER_ID
       AND A.GENDER IS NOT NULL
     GROUP BY A.USER_ID, TO_CHAR(B.SALES_DATE, 'YYYYMM'), A.GENDER
     ORDER BY TIMES, GENDER, USERS)
 GROUP BY TIMES, GENDER
 ORDER BY YEAR, MONTH, GENDER
 
-- SELECT *
--   FROM (
-- SELECT USER_ID,
--        COUNT(1)
--   FROM ONLINE_SALE
--   WHERE SALES_DATE BETWEEN TO_DATE('20220101', 'YYYYMMDD') AND TO_DATE('20220131', 'YYYYMMDD')
--   GROUP BY USER_ID)