-- 코드를 입력하세요
WITH USER_INFO_TMP AS 
    (
        SELECT USER_ID,
               COUNT(DISTINCT USER_ID) OVER() AS TOTAL_CNT
          FROM USER_INFO
         WHERE JOINED BETWEEN TO_DATE('20210101', 'YYYYMMDD') AND TO_DATE('20211231', 'YYYYMMDD')
    )

SELECT TO_CHAR(B.SALES_DATE, 'YYYY') AS YEAR
      ,TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH
      ,COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS
      ,ROUND(COUNT(DISTINCT A.USER_ID) / MAX(A.TOTAL_CNT), 1) AS PUCHASED_RATIO
  FROM USER_INFO_TMP A, ONLINE_SALE B
 WHERE A.USER_ID = B.USER_ID
 GROUP BY TO_CHAR(B.SALES_DATE, 'YYYY'), TO_CHAR(B.SALES_DATE, 'MM')
 ORDER BY YEAR, MONTH 
 
 
-- SELECT B.ONLINE_SALE_ID
--       ,A.USER_ID
--       ,B.PRODUCT_ID
--       ,B.SALES_AMOUNT
--       ,B.SALES_DATE
--       ,A.TOTAL_CNT
--   FROM USER_INFO_TMP A, ONLINE_SALE B
--  WHERE A.USER_ID = B.USER_ID