-- 코드를 입력하세요
SELECT '/home/grep/src/'||B.BOARD_ID||'/'||B.FILE_ID||B.FILE_NAME||B.FILE_EXT AS FILE_PATH
  FROM (SELECT BOARD_ID, 
              RANK() OVER(ORDER BY VIEWS DESC) RNK
         FROM USED_GOODS_BOARD ) A LEFT JOIN USED_GOODS_FILE B
    ON A.BOARD_ID = B.BOARD_ID
 WHERE A.RNK = 1
 ORDER BY FILE_PATH DESC