-- -- 코드를 입력하세요
SELECT TO_CHAR('/home/grep/src/') || A.BOARD_ID || '/' || B.FILE_ID || B.FILE_NAME || B.FILE_EXT AS FILE_PATH
FROM (SELECT BOARD_ID,
       ROW_NUMBER() OVER(ORDER BY VIEWS DESC) AS RNK_VIEW
  FROM USED_GOODS_BOARD) A LEFT JOIN USED_GOODS_FILE B
    ON A.BOARD_ID = B.BOARD_ID
 WHERE A.RNK_VIEW = 1
 ORDER BY B.FILE_ID DESC
