-- 코드를 입력하세요
SELECT A.WRITER_ID AS USER_ID
     , B.NICKNAME
     , B.CITY || ' ' || B.STREET_ADDRESS1 || ' ' || B.STREET_ADDRESS2 AS "전체주소"
     , SUBSTR(TLNO,1,3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) AS "전화번호"
  FROM 
    (SELECT WRITER_ID
       FROM USED_GOODS_BOARD
      GROUP BY WRITER_ID
     HAVING COUNT(1) >= 3) A LEFT JOIN USED_GOODS_USER B
   ON A.WRITER_ID = B.USER_ID
 ORDER BY 1 DESC